### ISSUE TITLE
Add Timings

### ISSUE THREAD

**Issue by Techcable** [WaterfallMC/Waterfall-Old#10]
Dump heiarchal data on how long portions of the code take.
Sampling data could be included someday too.

Im thinking a python script to analyze the data and print out critical subsections of the data.
I'd be willing to try and implement this (at least the timings and python script).

Im thinking just timing plugin events for now.
Async events would be included 

Example format:

```
"packet.chat" 12980
  "event.ChatEvent" 12900
    "net.evil.ChatFilterListener#destroyChat" 11000
    "net.stupid.ChatFilterListener#stupidStuff" 1600
    "net.smart.ChatFilstupidStuff"onChat" 300
```

The script would analyze and just display the evil listener, and its parents.

**Comment by punkeel** [comment]
Any update on this one ? :)

**Comment by Janmm14** [comment]
I think it is a valid idea to have inbuilt timings, however there are external tools like Yourkit available which do the same thing already, so the priority might not be that high.

**Comment by punkeel** [comment]
You wouldn't run YourKit in production, would you ? ;)

**Comment by RhvsW** [comment]
yes?

**Comment by Janmm14** [comment]
Thats a point.

**Comment by Techcable** [comment]
Plenty of people run yourkit in production.
You get the best performance metrics if you run it in production.

**Comment by punkeel** [comment]
You're right, @Techcable

**Comment by Techcable** [comment]
I now think this would be better handled by a sampling plugin, as suggested by Champ on IRC.
