### ISSUE TITLE
re-enable connection throttle

### ISSUE THREAD

**Issue by PhanaticD** [WaterfallMC/Waterfall-Old#12]
I see shit like this ALL the time

11:53:55 [INFO] [XxFire_BoyzxX] disconnected with: §cYou are already connected to this server!
11:53:55 [INFO] [XxFire_BoyzxX] disconnected with: §cYou are already connected to this server!
11:53:55 [INFO] [XxFire_BoyzxX] disconnected with: §f[Proxy] Lost connection to server.
11:53:55 [INFO] [XxFire_BoyzxX] <-> DownstreamBridge <-> [skygrid] has disconnected

I believe there is a client bug where you can connect multiple times in a row, I have reproduced it before myself when spam clicking my server on the multiplayer server list with laggy internet

its important that the connection throttle is only for new connections not pings

**Comment by Techcable** [comment]
Why was this even removed in the first place?
could we add a sanity throttle for pings so the server doesnt get DDOSed?

**Comment by Techcable** [comment]
Can merge [Bungee Patcher's Reimplement Throttle Patch](https://github.com/minotopiame/BungeeCordPatcher/blob/master/patches/0001-Re-Implement-throttle.patch) and their [Server List Ping Logging Patch](https://github.com/minotopiame/BungeeCordPatcher/blob/master/patches/0003-Optional-server-list-ping-logging-Add-IPs-to-the-log.patch).
I want @minecrafter 's opinion on this though.
We'll have to switch the messages from german to english.

**Comment by minecrafter** [comment]
@Techcable I would approve but I think putting the options under a `waterfall.yml` file would be a better idea.

**Comment by Techcable** [comment]
Alright, so we stuff our custom options in our own config?
I'll also do that for tab-throttling.

**Comment by minecrafter** [comment]
Yes. It keeps the main bungee.yml cleaner and produces a few less headaches (merge-wise) in case md_5 decides to merge these patches.

**Comment by Techcable** [comment]
I'm assuming this is fixed, but I can't join fast enough to reproduce.
@PhanaticD 
I'm enabling logging of throttled joins by default, but If you don't want this it can be disabled.
Just add "-Dwaterfall.log_throttled_joins=false"
