### ISSUE TITLE
Handle empty packets

### ISSUE THREAD

**Issue by Techcable** [WaterfallMC/Waterfall-Old#20]
According to @Byteflux 1.7 clients sometimes send empty packets.
[This line](https://github.com/WaterfallMC/Waterfall/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/Varint21FrameDecoder.java#L34) causes the client to be kicked when they do.

Since its a valid packet, we shouldn't kick the client.

We can't just ignore the packets, as that would allow a denial of service attack.

I think i'm going to limit the number of empty packets that can be sent to about 5 a second.
Apparently they don't send them that often.

**Comment by Techcable** [comment]
If anyone still experiences this issue, please say so.
I can't confirm this was fixed, since I don't know how to reproduce the empty packets.

**Comment by Aquazus** [comment]
Fixed for me

**Comment by Techcable** [comment]
This has been un-fixed by ab461f3

**Comment by minecrafter** [comment]
Re-fixed already (by ignoring the packets).
