### ISSUE TITLE
Bug that disconnects all players on a vanilla spigot server

### ISSUE THREAD

**Issue by NullOrNaN** [WaterfallMC/Waterfall-Old#22]
Simply put, this is a pretty bad bug as it appears to be able to crash everyone off of a Spigot server with simply using a forge-based client/FML. 

[Stack Trace](https://gist.github.com/MatthewM/296e3b05712a4ccc4284)

confirmed it has to be a Forge Client and no server side mods

**Comment by Techcable** [comment]
How do you reproduce it?
What mods do you have?

**Comment by NullOrNaN** [comment]
It has to be a Forge Client and no server side mods. Latest Waterfall at the time of writing (#69).

Spigot Version: git-Spigot-fdc1440-53fac9f (MC: 1.8.8) - Yes it's not the newest.

Forge Client: 1.8-11.14.4.1563
Forge Client Mods: 
CodeChickenCore 1.8-1.0.5.36-universal 
CoreChickenLib 1.8-1.1.2.133-universal.
NotEnoughItems 1.8-1.0.5.104-universal
Optifine 1.8.0_HD_U_G7
TabbyChat 2.0.0-beta3.1
MnM Utils 0.3.1

(Shouldn't matter below)
LiteLoader: Not sure Version
Litemods: 1.5.18_for_1.8a
WorldEditCUI 1.8.0_03_lite_mc1.8

**Comment by minecrafter** [comment]
Unable to verify with a stock Forge client and no server side mods.

![](https://i.imgur.com/092Zud7.png)

**Comment by Techcable** [comment]
@MatthewM 
What are 'litemods'

**Comment by NullOrNaN** [comment]
It's LiteLoader. It's a loader that can chain to FML and allow some other mods. Also.. we all derp.. See link.

[BungeeTabListPlus?](https://gist.github.com/MatthewM/296e3b05712a4ccc4284#file-fml-bug-L11)
