### ISSUE TITLE
Disconnect to 1.7.10 client(s) on certain characters

### ISSUE THREAD

**Issue by NullOrNaN** [WaterfallMC/Waterfall-Old#25]
It looks like with VentureChat, KCauldron, and Waterfall.

Additional Info:
Known Bad Characters: %
[Gist of kick/softcrash](https://gist.github.com/MatthewM/16ed93710a2556533a1b)
[Seemingly related bug](https://github.com/WaterfallMC/Waterfall/issues/21)
Waterfall Version: This server is running Waterfall version git:Waterfall-Bootstrap:1.8-SNAPSHOT:e97c309:73 by the Waterfall team

**Comment by minecrafter** [comment]
Unable to reproduce under MultiverseChat (the old name) 1.9.4 (default configuration), KCauldron 1.7.10-1614.12, and Waterfall build 79.

If you can give us exact versions of KCauldron and VentureChat, and your configuration for VentureChat, then we'll try reproducing again.

**Comment by NullOrNaN** [comment]
I'm using the current version of VentureChat (2.7.0). I'll check my KCauldron version and get you the config in a few. Going to try your version of the plugin first.

**Comment by minecrafter** [comment]
I was able to reproduce the issue, but this looks like a KCauldron plugin compatibility issue to me, not an issue with Waterfall.
