### ISSUE TITLE
Some client with forge cannot join server

### ISSUE THREAD

**Issue by jiongjionger** [WaterfallMC/Waterfall-Old#30]
It's just timeout.

**Comment by minecrafter** [comment]
There's not enough information to fix the problem.

What version of Forge? Mods and mod versions? Version of Waterfall? Your server versions?

**Comment by jiongjionger** [comment]
A lot of players can not join the server, the players are using 1.8 of the client. According to my own test, I found that even if only the installation of forge without mods, can not join the server.

Waterfall: latest version
Server: PaperSpigot 1.8.8
Mods: even without Mod
Forge: such as 11.14.4.1579

**Comment by Techcable** [comment]
What error do they get?
What do you see in the console?

**Comment by jiongjionger** [comment]
1. no error message in console
2. unable to enter server(timeout)
3. client without forge can join server

**Comment by minecrafter** [comment]
Unable to verify

**Comment by jiongjionger** [comment]
@minecrafter
This problem still exists in the latest :(

`io.netty.util.concurrent.SingleThreadEventExecutor runAllTasks : A task raised an exception.
java.lang.NullPointerException
    at net.md_5.bungee.UserConnection.init(UserConnection.java:201)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:522)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Unknown Source)`

**Comment by jiongjionger** [comment]
I deleted all the plugin, the problem still exists.

**Comment by minecrafter** [comment]
Is your server in offline mode?

**Comment by jiongjionger** [comment]
Yes, my server in offline mode.

**Comment by minecrafter** [comment]
Give https://ci.getwaterfall.xyz/repository/download/Waterfall_Build/533:id/waterfall.jar a try.

**Comment by jiongjionger** [comment]
Thank you very much, this issue has been fixed!

**Comment by minecrafter** [comment]
Thanks, it's merged now.
