### ISSUE TITLE
Incompatibility with plugin Bungee Admin Tools (BAT)

### ISSUE THREAD

**Issue by Malachiel87** [WaterfallMC/Waterfall-Old#32]
Error on launch, using waterfall #95, is the only bungee plugin that dont like it:

```
08:42:57 [GRAVE] [BungeeAdminTools] Your BungeeCord build (#95) is not supported. Please use at least BungeeCord #878
08:42:57 [GRAVE] [BungeeAdminTools] BAT is going to shutdown ...
```

**Comment by dwaynehulsman** [comment]
I added a bungee version bypass check in a fork. https://github.com/xxroltsxx/BungeeAdminTools
Delete your existing config.yml and set bungeeCheck to false

**Comment by alphartdev** [comment]
Was also going to configure the bungeecheck as optionnal but probably going to ask to create a file rather than just a config option. I hope you don't mind if I borrow a bit of your code @xxroltsxx?

**Comment by Techcable** [comment]
@xion87 
This is an issue with BungeeAdminTools, it thinks we are running an outdated bungee, and doesn't realize we are a fork.

**Comment by dwaynehulsman** [comment]
No problem at all @alphartdev I did a pull request to a few days ago.
