### ISSUE TITLE
TCP Options ?

### ISSUE THREAD

**Issue by punkeel** [WaterfallMC/Waterfall-Old#35]
Hello,

I have not tested myself, and thus I create this "Issue", but I think BungeeCord could benefit from Netty's TCP tweaking.

Some options I think might help : 
TCP_NODELAY, SO_READ, SO_WRITE.

I'm not saying BungeeCord is laggy, but ... It feels like the latency is always increasing, then it's reset when switching server.

**Comment by harrydevane** [comment]
https://github.com/WaterfallMC/Waterfall/pull/36

**Comment by punkeel** [comment]
Thanks (could have opened the PR myself, in fact)

Let's close this one, then!
