### ISSUE TITLE
§ is showing as an A symbol in bungee messages file

### ISSUE THREAD

**Issue by Twi5TeD** [WaterfallMC/Waterfall-Old#38]
how can i fix my issue of the § symbol showing as the A symbol?

**Comment by phase** [comment]
That's your encoding. Try using Notepad++.

**Comment by Twi5TeD** [comment]
i used notepad++ with encoding set to utf-8

**Comment by phase** [comment]
Oh wait try normal Notepad. I forget which one breaks it.

**Comment by Ichbinjoe** [comment]
Sublime Text will work. Either way, this is a file reader issue.

**Comment by Techcable** [comment]
Actually, it looks like this was an issue on our end.
We were using ACII instead of UTF-8, so you would've had to use character escapes.

**Comment by kashike** [comment]
https://github.com/WaterfallMC/Waterfall/commit/9411a94060dc4cab61418295e829be6a51fb6773

**Comment by Twi5TeD** [comment]
Has waterfall updated for 1.9 and 1.8 support

**Comment by dyanakiev** [comment]
Yes. wget -O Waterfall.jar https://getwaterfall.xyz/builds/latest

**Comment by Twi5TeD** [comment]
thanks
