### ISSUE TITLE
Username is null (join-throttling)

### ISSUE THREAD

**Issue by Krymonota** [WaterfallMC/Waterfall-Old#45]
I see the following message in the console / log when a player gets join-throttled:
`19:08:27 [INFO] null at XX.X.X.XX was join-throttled`

It seems like [`getName()`](https://github.com/WaterfallMC/Waterfall/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L591) in [`InitialHandler`](https://github.com/WaterfallMC/Waterfall/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java) returns `null` during the [`Handshake handling`](https://github.com/WaterfallMC/Waterfall/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L279).

**Comment by minecrafter** [comment]
Fixed

**Comment by Techcable** [comment]
Why revert the entire commit?
Why not just fix the code in question to only show ips?

**Comment by minecrafter** [comment]
I already fixed it but never mentioned the issue.

**Comment by Techcable** [comment]
Yeah but why can't we still throttle joins at the handshake packet?

**Comment by minecrafter** [comment]
Personal taste (I prefer consistency in messaging).

That being said, I have no objections to changing it back.
