### ISSUE TITLE
Don't generate messages.properties

### ISSUE THREAD

**Issue by Ismael-GT** [WaterfallMC/Waterfall-Old#46]
Hello,

In the new version is not Automatically generated "messagges.properties"
http://prntscr.com/amgblc

Regards Ismael.

**Comment by Janmm14** [comment]
@iisma1 This is intended because Waterfall now uses the new BungeeCord implemntation with an optional messages.properties in the root folder.

**Comment by Techcable** [comment]
So basically you just create a messages.properties file and change the messages you want.
