### ISSUE TITLE
Colors not formatting correctly

### ISSUE THREAD

**Issue by CullanP** [WaterfallMC/Waterfall-Old#47]
When using § to format colors with this plugin in bungeecord it works https://www.spigotmc.org/resources/bungeealiases.4107/, while in waterfall it does not. It shows up as question marks http://puu.sh/o60zV/10ab3c1512.png

**Comment by minecrafter** [comment]
Probably a plugin issue

**Comment by Techcable** [comment]
He says it works on bungeecord.

**Comment by minecrafter** [comment]
Your configuration probably isn't being saved in the default system charset (most platforms aside from Windows likes UTF-8), hence the question mark.

**Comment by Techcable** [comment]
@CullanP have you tried that?

**Comment by CullanP** [comment]
@Techcable Trying it now.
