### ISSUE TITLE
Messagess

### ISSUE THREAD

**Issue by kukubaczek** [WaterfallMC/Waterfall-Old#51]
Can you add messages editing without editing jar?

**Comment by LuminousLoreBloom** [comment]
You already can since https://github.com/WaterfallMC/Waterfall/commit/f265f7c5944d195ffa070016a63d893e9a2d8cb1, I believe you have to copy the file yourself from here https://github.com/WaterfallMC/Waterfall/blob/master/proxy/src/main/resources/messages.properties

**Comment by kukubaczek** [comment]
Ok, thanks!

W dniu niedziela, 10 kwietnia 2016 Mystiflow notifications@github.com
napisał(a):

**Comment by Janmm14** [comment]
Actually you can do the same in bungeecord, as a side note.
