### ISSUE TITLE
InitialHandler - encountered exception

### ISSUE THREAD

**Issue by mgl** [WaterfallMC/Waterfall-Old#54]
I'm using latest build and when I ping the bungee from my client in the server list I get these errors.
This error appeared on latest waterfall builds.

http://pastebin.com/8gMc0Fjt
http://pastebin.com/pg19eHyY
http://pastebin.com/QRP463R3

> 01:37:21 [GRAVE] [/HIDDEN:26773] <-> InitialHandler - encountered exception
> io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
>     at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.callDecode(DirectByteToMessageDecoder.java:312)
>     at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.channelRead(DirectByteToMessageDecoder.java:150)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
>     at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:71)
>     at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.callDecode(DirectByteToMessageDecoder.java:281)
>     at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.channelRead(DirectByteToMessageDecoder.java:150)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
>     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
>     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
>     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
>     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
>     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
>     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
>     at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1190)
>     at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1176)
>     at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:587)
>     at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:39)
>     at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.callDecode(DirectByteToMessageDecoder.java:281)
>     ... 17 more
> 01:37:21 [GRAVE] avr. 14, 2016 1:37:21 AM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
> AVERTISSEMENT: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
> io.netty.channel.ChannelPipelineException: net.md_5.bungee.protocol.Varint21FrameDecoder.handlerRemoved() has thrown an exception.
>     at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:530)
>     at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
>     at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:351)
>     at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:798)
>     at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:767)
>     at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:759)
>     at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:743)
>     at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:663)
>     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
>     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)
>     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
>     at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): PooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 1)
>     at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
>     at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172)
>     at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:724)
>     at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:717)
>     at io.github.waterfallmc.waterfall.DirectByteToMessageDecoder.handlerRemoved(DirectByteToMessageDecoder.java:123)
>     at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
>     ... 11 more
> <

**Comment by Leymooo** [comment]
+1
http://pastebin.com/C5hriSSS

**Comment by Techcable** [comment]
Should be fixed by 9a1ab6bbf81c98c7f592ad3414ba9a17cb14fe68
Bug me if its not.
