### ISSUE TITLE
Internal Exception: net.minecraft.util.io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

### ISSUE THREAD

**Issue by Kira07** [WaterfallMC/Waterfall-Old#56]
A lot of 1.7 players are getting disconnected with this error:

nektow2003 lost connection: Internal Exception: net.minecraft.util.io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

I use the latest version.

**Comment by ghost** [comment]
Same.

**Comment by minecrafter** [comment]
Duplicate of #48
