### ISSUE TITLE
Modify/Remove the 'Waterfall' in the version info

### ISSUE THREAD

**Issue by ghost** [WaterfallMC/Waterfall-Old#60]
Hi, have to change this information? I'm talking about the version on the server list: https://scr.hu/PRGG6V

**Comment by Techcable** [comment]
Change 'gameVersion' in waterfall.yml

**Comment by ghost** [comment]
What does it have to do with my question?

I want to change this for example "Only MC 1.7/1.8"

**Comment by Janmm14** [comment]
Change "gameVersion" in waterfall.yml

**Comment by ghost** [comment]
What does it have to do with my question?

**Comment by Janmm14** [comment]
Dude because I repeated the answer, you should think about it and know that you need to change that configuration value to whatever you want to achieve your goal.

Thanks.

If it does not work immediately, you might want to /greload or restart your Waterfall server.

**Comment by ghost** [comment]
Dude, I don't want to change the version, just the message.

**Comment by Janmm14** [comment]
We know and we gave you the appropiate answer for that.

**Comment by minecrafter** [comment]
This will change the message. If you're hesitant, then ServerListPlus should work perfectly fine with Waterfall.

**Comment by ghost** [comment]
I want to change the invalid version message.

**Comment by Janmm14** [comment]
Then change that configuration value. It does not chage version of Waterfall or spigot version or BungeeCord version or any plugin version. It just changes that specific version you mentioned and screenshotted.

Thanks.

Instead of writing further answers, just try it out please.

**Comment by ghost** [comment]
I want to change the invalid version message not the available versions...

**Comment by Janmm14** [comment]
@minecrafter @Techcable Please reopen the issue. He is actually correct in that he can't remove the leading `Waterfall` from the version which is sent.

**Comment by Techcable** [comment]
This is expected behavior for spigot/bungee/paper/waterfall.
`getModName() + supportedVersions` is what the version string almost always is.

**Comment by ghost** [comment]
How to change it? Ok, I see now how to edit it, but I would have to edit the source. How to do it?

**Comment by Janmm14** [comment]
Currently editing is possible with plugins or source code modification.

**Comment by ghost** [comment]
Can you help with doing it?

**Comment by Leymooo** [comment]
https://github.com/Dimatert9/Waterfall/commit/574f1d7f11f18c873a0d2c8fe537e859019de081
https://github.com/Dimatert9/Waterfall/commit/78ba3cd0076d3341609dd9173719b7de1d3af268

this can help.

**Comment by CzlowiekKuktas** [comment]
I said i know where it it, but I don't know how to do it.

**Comment by ghost** [comment]
I know where to change it, but I don't know how.

**Comment by ghost** [comment]
?

**Comment by Janmm14** [comment]
@CzlowiekKuktas 
You download this project as ZIP or clone it with git.
Then you change that what you want.
Next you need to download the java development kit (jdk) (preferably latest one) and maven 3 (latest version as usual).
Then you navigate with your command line into the root folder of this project and execute `mvn clean install`.
After that, go into `bootstrap/target` and you have your new `BungeeCord.jar`.

**Comment by ghost** [comment]
@Janmm14 How to install Maven?

**Comment by Leymooo** [comment]
@CzlowiekKuktas  google?

**Comment by ghost** [comment]
How to edit the source with Eclipse for example?

Where can I get all resources that BungeeCord/Waterfall need?

**Comment by Janmm14** [comment]
@CzlowiekKuktas Maven is used for the things BungeeCord / Waterfall needs. Just follow my instructions. Do not use eclipse for compilation. To install maven, please google.

**Comment by kamcio96** [comment]
download maven, unzip it, run in project folder:
"C:/something/else/downloads/apache-maven-version/bin/mvn.bat" clean install

**Comment by CzlowiekKuktas** [comment]
@Janmm14 @kamcio96 https://scr.hu/w2r69v

**Comment by ghost** [comment]
@kamcio96 I entered the Waterfall-master folder and run this command, something happened. I have the jar. Now what?

**Comment by Ichbinjoe** [comment]
This has turned into a help issue. Please bring this to the forums, keep
issues clean

**Comment by ghost** [comment]
It is heading to the end.
@Janmm14 @kamcio96 can you help?

**Comment by kamcio96** [comment]
get bootstrap/target/waterfall-version.jar
and run

**Comment by kamcio96** [comment]
or you can just write plugin xDDDD

**Comment by ghost** [comment]
@kamcio96 @Janmm14 Ye, I have original Waterfall, and I need to change something. How?

**Comment by Janmm14** [comment]
@CzlowiekKuktas one last comment from me here: in the source files you go in with a text editor, the places are already mentioned by Dimart9. Edit one of the two places. After saving, run the mvn ... command.

**Comment by ghost** [comment]
@Janmm14 Last question: Can I change the invalid version message to the normal online player count?

**Comment by Techcable** [comment]
@CzlowiekKuktas That is outside the scope of waterfall, and should be handled in a plugin.
