### ISSUE TITLE
Connection Throttled

### ISSUE THREAD

**Issue by ygtdmn** [WaterfallMC/Waterfall-Old#61]
In build #196 nobody can join the server. In console it says connection was throttled and players getting error all time. It says connection is throttled.

**Comment by Janmm14** [comment]
Do not use the last 5 builds (If I counted correctly).

Issue is already identified by me.

One can see here what is done wrong in code: https://github.com/WaterfallMC/Waterfall/commit/06d647ea8c14a0e62ac320732423f65d0aa9ce42#commitcomment-17252124

**Comment by Techcable** [comment]
Duplicate of #26
