### ISSUE TITLE
disconnect DownstreamBridge <-> [hub18] - encountered exception

### ISSUE THREAD

**Issue by minecraft7net** [WaterfallMC/Waterfall-Old#69]
hi,

i have problem with disconnectin players after searching and searching i see that this may be something waterfall <-> chatmanager ? i think i have this only on servers with bungeesuite chat.

any chance to patch this on waterfall - please? :)
version git:Waterfall-Bootstrap:1.9-SNAPSHOT:cecf132:202
02:50:19 [INFO] Loaded plugin BungeeSuite version 0.51b-99 by Bloodsplat

pastebin
http://pastebin.com/6KiVP9Tq

proxy1
cat proxy.log.0 | grep -i encountered  | wc -l
263

proxy2
cat proxy.log.0 | grep -i encountered | wc -l
259

:-(((((((

**Comment by minecrafter** [comment]
This sounds like an issue with BungeeSuite, not Waterfall.

**Comment by minecraft7net** [comment]
ok after check with never version of bungeesuite 1.9 and bungeesuitechat 1.9 - the same.

http://pastebin.com/aP9Wbj7r
https://www.spigotmc.org/resources/bungeesuite-1-9.19679/
https://www.spigotmc.org/resources/bungeesuitechat-1-9.19987/

the error is OK but meybe waterfall could add something to handle this ? just ignore this message and don't send chat message and don't kick player ?
