### ISSUE TITLE
Waterfall is now not support clients 1.7

### ISSUE THREAD

**Issue by Sitmobedaf** [WaterfallMC/Waterfall-Old#77]
Clients ver. 1.7.10 can not connect to Waterfall (https://ci.aquifermc.org/job/Waterfall/9/)

Config: game_version: 1.7.x, 1.8.x

**Comment by minecrafter** [comment]
The new patch-based Waterfall drops 1.7 support. We will be adding support to 1.7 in a separate fork to make maintenance easier.
