### ISSUE TITLE
BungeeCord packet flood

### ISSUE THREAD

**Issue by Sitmobedaf** [WaterfallMC/Waterfall-Old#78]
Ability to ignore packet flood?

https://youtu.be/8zeDVlLw7q4

On use stresser (http://quezstresser.com/) BungeeCord cases to connections players and ping packets. Wherein Dedicated server online, and 0% packet loss.

**Comment by Janmm14** [comment]
I can't look that vid because I'm in germany and music issues.

**Comment by minecrafter** [comment]
Waterfall isn't going to ignore packet floods for you. That's what firewalls and DDoS protection are for.
