### ISSUE TITLE
Waterfall

### ISSUE THREAD

**Issue by ghost** [WaterfallMC/Waterfall-Old#79]
Will this version of Waterfall be continued? I don't see the problem with randomly kicking players with proxy error, but there are few errors in the console. I think everything else is working fine.
@Techcable 
@minecrafter 
@kashike

**Comment by ghost** [comment]
Problem still exists, lol.

**Comment by Janmm14** [comment]
This version won't be continued.

**Comment by ghost** [comment]
Did you think about adding the 1.7 feature?

**Comment by minecrafter** [comment]
That's what Travertine is

**Comment by ghost** [comment]
"This repository is empty."

**Comment by ghost** [comment]
@minecrafter When will Travertine be ready? :)

**Comment by kamcio96** [comment]
Why don't just use newest version? It's better, don't have bugs, more performance. So why not?

**Comment by sgdc3** [comment]
@kamcio96 i think he needs 1.7 support to use forge compatible servers like kcauldron and thermos

**Comment by kamcio96** [comment]
Definitely not

**Comment by ghost** [comment]
I want to have server with multiple version support - from 1.7 to 1.9 or newer.

**Comment by Janmm14** [comment]
@CzlowiekKuktas Use new build with ProtocolSupportBungee.
