### ISSUE TITLE
Only pull from master branch

### ISSUE THREAD

**Issue by DenWav** [WaterfallMC/Waterfall-Old#9]
Here's an updated URL that will only pull from the master branch (it's configured to auto-build PR's as well).

`https://tc.demonwav.com/guestAuth/app/rest/builds/buildType:Waterfall_Build,branch:<default>/artifacts/content/waterfall.jar`

This is what I'm referencing: https://github.com/ProjectWaterfall/Waterfall/commit/0ac6acdb41d547fb7f658f772b44c3ac4b265d44

**Comment by minecrafter** [comment]
I fixed this in c7b62e6 (before I went to bed).
